### ISSUE TITLE
Missing README :)

### ISSUE THREAD

**Issue by redox** [arnaudlewis/algolia-server#1]
I would love to understand how to run the project and I'm not familiar with Scala/Play!; do you mind adding a README and eventually deploying the project somewhere?

**Comment by redox** [comment]
Don't forget to tell us how to seed the DB.

**Comment by arnaudlewis** [comment]
@redox It should be ok, i filled the Readme with all the instructions. I wasn't sure if you wanted me to fill the database directly or just send pings from another server just to simulate real life so i explain how to do both. Please tell me if you need more informations.

**Comment by redox** [comment]
👍
